[package]
name = "dayer"
version = "0.1.0"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]

[dependencies]
tar = "0.3"
adorn = "0.1.1" # wasn't working in dev-deps?
maplit = "0.1.2" # also doesn't work in dev-deps

[dev-dependencies]
tempdir = "0.3"
