[package]
name = "dayer"
version = "0.1.1"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]

[dependencies]
tar = "0.3.3"
adorn = "0.1.2" # wasn't working in dev-deps?

[dev-dependencies]
maplit = "0.1.2"
tempdir = "0.3"
